NewMeteoWeb/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace NewMeteoWeb.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View("~/Pages/Index.cshtml");
        }

        public IActionResult UserList()
        {
            return View();
        }
    }
}

NewMeteoWeb/Controllers/ServerRequestController.cs
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Security.Claims;
using System.Text;
using System.Threading.Tasks;
using static NewMeteoWeb.Pages.AuthorizeModel;
using static NewMeteoWeb.ServerRequestForms;

namespace NewMeteoWeb.Controllers
{

    public class ServerRequestController : Controller
    {
        [AllowAnonymous]
        public async Task<ActionResult> Authorize(string name, string password)
        {
            HttpClient client = new HttpClient();
            var u = new AuthRequestForm { Name = name, Password = password, Type = "Sign in" };
            var json = JsonConvert.SerializeObject(u);
            var data = new StringContent(json, Encoding.UTF8, "application/json");
            var webRequest = new HttpRequestMessage {
                RequestUri = new Uri("http://localhost:8888/auth"),
                Content = data
            };
            var response = client.Send(webRequest);
            var respText = response.Content.ReadAsStringAsync().Result;
            if (respText != "ok")
            {
                
                return new ContentResult { Content = respText };
            }
            else
            {
                SessionManager.CurrentUser = name;
                Response.Cookies.Append("currentUser", name);
                return new ContentResult { Content = "https://" + Request.Host.Value };
            }
        }

        public async Task<ActionResult> LogOut()
        {
            foreach (var cookie in HttpContext.Request.Cookies)
            {
                if (cookie.Key == "currentUser")
                    Response.Cookies.Delete(cookie.Key);
            }
            SessionManager.CurrentUser = "";
            return new ContentResult { Content = "https://" + Request.Host.Value };
        }

        [HttpPost]
        public async Task<ActionResult> AddUser(string name, string password, string type)
        {
            if (!Request.Cookies.ContainsKey("currentUser"))
            {
                return new ContentResult { Content = "Authorize" };
            }
            HttpClient client = new HttpClient();
            var u = new AuthRequestForm { Name = name, Password = password, Type = type };
            var json = JsonConvert.SerializeObject(u);
            var data = new StringContent(json, Encoding.UTF8, "application/json");
            var webRequest = new HttpRequestMessage
            {
                RequestUri = new Uri("http://localhost:8888/auth"),
                Content = data
            };
            var response = client.Send(webRequest);
            var respText = response.Content.ReadAsStringAsync().Result;
            return new ContentResult { Content = respText };
        }

        [HttpGet]
        public async Task<ActionResult> DeleteUser()
        {
            if (!Request.Cookies.ContainsKey("currentUser"))
            {
                return new ContentResult { Content = "Authorize" };
            }
            HttpClient client = new HttpClient();
            var webRequest = new HttpRequestMessage
            {
                RequestUri = new Uri("http://localhost:8888/deluser/" + Request.Query.Keys.First())
            };
            var response = client.Send(webRequest);
            var respText = response.Content.ReadAsStringAsync().Result;
            if (respText != "ok")
            {
                return new ContentResult { Content = respText };
            }
            else
            {
                return new ContentResult { Content = "https://" + Request.Host.Value };
            }
        }

        [HttpGet]
        public async Task<ActionResult> DeleteMap()
        {
            if (!Request.Cookies.ContainsKey("currentUser"))
            {
                return new ContentResult { Content = "Authorize" };
            }
            HttpClient client = new HttpClient();
            var webRequest = new HttpRequestMessage
            {
                RequestUri = new Uri("http://localhost:8888/delmap/" + Request.Query.Keys.First())
            };
            var response = client.Send(webRequest);
            var respText = response.Content.ReadAsStringAsync().Result;
            if (respText != "ok")
            {
                return new ContentResult { Content = respText };
            }
            else
            {
                return new ContentResult { Content = "https://" + Request.Host.Value };
            }
        }

    }
}

NewMeteoWeb/Pages/Authorize.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace NewMeteoWeb.Pages
{
    public class AuthorizeModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

NewMeteoWeb/Pages/Home/Authorize.cshtml.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace NewMeteoWeb.Pages
{
    public class AuthorizeModel : PageModel
    {

        public void OnGet()
        {
        }
    }
}

NewMeteoWeb/Pages/Home/MapList.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Newtonsoft.Json;

namespace NewMeteoWeb.Pages.Home
{
    public class MapListModel : PageModel
    {
        [BindProperty]
        public List<MapDB> list { get; set; }

        public async Task<IActionResult> OnGet()
        {
            HttpClient client = new HttpClient();
            var webRequest = new HttpRequestMessage(HttpMethod.Get, "http://localhost:8888/getallmaps");
            var response = client.Send(webRequest);
            var respText = response.Content.ReadAsStringAsync().Result;
            list = JsonConvert.DeserializeObject<List<MapDB>>(respText);

            return Page();
        }
    }
}

NewMeteoWeb/Pages/Home/UserList.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Newtonsoft.Json;

namespace NewMeteoWeb.Pages
{
    public class UserListModel : PageModel
    {
        [BindProperty]
        public List<User> list { get; set; }

        public async Task<IActionResult> OnGet()
        {
            HttpClient client = new HttpClient();
            var webRequest = new HttpRequestMessage(HttpMethod.Get, "http://localhost:8888/getallusers");
            var response = client.Send(webRequest);
            var respText = response.Content.ReadAsStringAsync().Result;
            list = JsonConvert.DeserializeObject<List<User>>(respText);

            return Page();
        }
    }
}

NewMeteoWeb/Pages/Home/Authorize.cshtml
@page
@model NewMeteoWeb.Pages.AuthorizeModel
@{
}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Вход</title>
    <link rel="stylesheet" href="~/css/style.css" />
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
</head>
<body>
    <div class="window-back"></div>
    <div class="window authorization-window">
        <form class="signIn" method="post">
            <h2>Войти</h2>
            <label for="name">Имя:</label>
            <input type="text" name="name" value="">
            <label for="password">Пароль:</label>
            <input type="password" name="password" value="">
            @Html.Hidden("type", "Sign in")
            <button type="submit" name="signIn-accept">Ok</button>
            <a class="changeSignType">Регистрация</a> 
        </form>
        <form class="signUp" method="post">
            <h2>Зарегистрироваться</h2>
            <label for="name">Имя:</label>
            <input type="text" name="name" value="">
            <label for="password">Пароль:</label>
            <input type="password" name="password" value="">
            @Html.Hidden("type", "Sign up")
            <button type="submit" name="signUp-accept">Ok</button>
            <a class="changeSignType">Уже есть аккаунт</a>
        </form>
        <p class="response-text"></p>
    </div>

    <script type="text/javascript">
        $(".signUp").hide();

        $(function () {
            $(".signIn").submit(function (e) {
                e.preventDefault();
                $(".response-text").text("");
                $.ajax({
                    type: "POST",
                    url: '@Url.Action("Authorize", "ServerRequest")',
                    data: $(this).serialize(),
                    dataType: "json",
                    error: function (response) {
                        
                        if (response.responseText.startsWith("https://")) {
                            window.location.replace(response.responseText);
                            console.log(response.responseText);
                        }
                        else {
                            $(".response-text").text(response.responseText);
                        }
                    }
                });
            })
        });
    </script>
</body>
</html>

NewMeteoWeb/Pages/Home/MapList.cshtml
@page
@model NewMeteoWeb.Pages.Home.MapListModel
@{
    ViewData["Title"] = "MapList";
    Layout = "~/Pages/Shared/_Layout.cshtml";
}

<div class="response-text"></div>
<div class="list">
    @foreach (var item in Model.list)
    {
        <div>
            <p>
                @Html.DisplayFor(m => item.Name)
            </p>
            <img class="delete-button" src="~/delete.png" />
        </div>
    }
</div>

<script type="text/javascript">

    $(function () {
        $(".delete-button").click(function (e) {
            $.ajax({
                type: "GET",
                url: '@Url.Action("DeleteMap", "ServerRequest")',
                data: e.currentTarget.parentElement.innerText,
                contentType: "text/plain",
                error: function (response) {
                    $(".response-text").text(response.responseText);
                },
                success: function () {
                    location.reload();
                }

            });
        })
    });
</script>

NewMeteoWeb/Pages/Home/UserList.cshtml
@page
@model NewMeteoWeb.Pages.UserListModel
@{
    ViewData["Title"] = "UserList";
    Layout = "~/Pages/Shared/_Layout.cshtml";
}

<div class="response-text"></div>
<div class="list">
    @foreach (var item in Model.list)
    {
        <div>
            <p>
                @Html.DisplayFor(m => item.Name)
            </p>
            <img class="delete-button" src="~/delete.png" />
        </div>
    }
    <form method="post">
        <input type="text" name="name">
        <input type="password" name="password">
        @Html.Hidden("type", "Sign up")
        <button type="submit" name="signUp-accept">Ok</button>
    </form>
</div>

<script type="text/javascript">
    $(function () {
        $("form").submit(function (e) {
            e.preventDefault();
            $(".response-text").text("");
            $.ajax({
                type: "POST",
                url: '@Url.Action("AddUser", "ServerRequest")',
                data: $(this).serialize(),
                dataType: "json",
                error: function (response) {
                    if (response.responseText == "ok") {
                        location.reload();
                    }
                    else {
                        $(".response-text").text(response.responseText);
                    }
                }
            });
        })
    });

    $(function () {
        $(".delete-button").click(function (e) {
            $.ajax({
                type: "GET",
                url: '@Url.Action("DeleteUser", "ServerRequest")',
                data: e.currentTarget.parentElement.innerText,
                contentType: "text/plain",
                error: function (response) {
                    $(".response-text").text(response.responseText);
                },
                success: function () {
                    location.reload();
                }

            });
        })
    });
</script>